version: 0.2

env:
  variables:
    REPOSITORY_URI: 732203471303.dkr.ecr.ap-south-1.amazonaws.com/demo
    IMAGE_TAG: latest

phases:

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $REPOSITORY_URI

  build:
    commands:
      - echo Build Docker image started...
      - docker build -t demo .
      - docker tag demo:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Build completed successfully

      # THIS FILE TELLS ECS WHAT IMAGE TO DEPLOY (IMPORTANT)
      - printf '[{"name":"my-repo","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
